# Generated by Django 5.1.3 on 2024-11-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('Artist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Biography', models.TextField()),
                ('Genre', models.TextField(max_length=100)),
                ('Songs', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Subscription_type', models.IntegerField(default=0)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('Album_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Release_date', models.DateField()),
                ('Artist_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artists')),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('Track_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Artists_ID', models.JSONField(default=list)),
                ('Title', models.CharField(max_length=100)),
                ('Genre', models.TextField(max_length=100)),
                ('Duration', models.IntegerField(default=0, max_length=1000)),
                ('File_Path', models.CharField(max_length=255)),
                ('Play_count', models.IntegerField(default=0)),
                ('Album_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.albums')),
            ],
        ),
        migrations.CreateModel(
            name='User_Follow_Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Following', models.JSONField(default=list)),
                ('Followed_by', models.JSONField(default=list)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('Playlist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Created_at', models.DateField()),
                ('Tracks', models.JSONField(default=list)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
            ],
        ),
    ]
